/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPreferences } from './userPreferences';
import { Group } from './group';
import { Category } from './category';
import { Claims } from './claims';
import { CurrencySeparator } from './currencySeparator';
import { FeatureConfig } from './featureConfig';
import { UserView } from './userView';
import { Icon } from './icon';
import { Tag } from './tag';
import { CurrencySymbolPosition } from './currencySymbolPosition';
import { About } from './about';


export interface AppData { 
    about: About;
    claims: Claims;
    /**
     * Groups in the system
     */
    groups: Array<Group>;
    /**
     * Users in the system
     */
    users: Array<UserView>;
    userPreferences: UserPreferences;
    featureConfig: FeatureConfig;
    /**
     * Categories in the system
     */
    categories: Array<Category>;
    /**
     * Tags in the system
     */
    tags: Array<Tag>;
    /**
     * JWT token
     */
    jwt?: string;
    /**
     * Refresh token
     */
    refreshToken?: string;
    /**
     * Currency display
     */
    currencyDisplay: string;
    currencyThousandthsSeparator?: CurrencySeparator;
    currencyDecimalSeparator?: CurrencySeparator;
    currencySymbolPosition?: CurrencySymbolPosition;
    /**
     * Whether to hide decimal places
     */
    currencyHideDecimalPlaces?: boolean;
    /**
     * Icons in the system
     */
    icons: Array<Icon>;
    /**
     * The calling user\'s effective app-level permissions. Deliberately typed as plain strings rather than the Permission enum: this is server-resolved data, not a contract. A granted entry may be a wildcard (e.g. \"app.*\"), which is not an enum member, and a client built before a newly added permission must still be able to parse the payload. Clients match these with the wildcard matcher.
     */
    appPermissions: Array<string>;
    /**
     * The calling user\'s effective group-level permissions, keyed by group id. Plain strings for the same reason as appPermissions.
     */
    groupPermissions: { [key: string]: Array<string>; };
    /**
     * The categories the calling user may use in each group, keyed by group id. Filtered to the user\'s group-role grants (the full pool when unrestricted). Non-admins receive categories only through this map.
     */
    groupCategories?: { [key: string]: Array<Category>; };
    /**
     * The tags the calling user may use in each group, keyed by group id. Filtered to the user\'s group-role grants (the full pool when unrestricted). Non-admins receive tags only through this map.
     */
    groupTags?: { [key: string]: Array<Tag>; };
}
export namespace AppData {
}


