/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterOperation } from './filterOperation';


export interface CustomFieldFilter { 
    /**
     * ID of the custom field to filter by
     */
    customFieldId?: number;
    operation?: FilterOperation;
    value?: any | null;
}
export namespace CustomFieldFilter {
}


