/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OidcProviderSummary } from './oidcProviderSummary';


export interface FeatureConfig { 
    /**
     * Whether AI powered receipts are enabled
     */
    aiPoweredReceipts: boolean;
    /**
     * Whether local sign up is enabled
     */
    enableLocalSignUp: boolean;
    /**
     * Composed deep link the desktop login page encodes as a QR; empty unless the login QR is enabled with a mobile server URL
     */
    loginQrUrl?: string;
    /**
     * Enabled OIDC identity providers, so a login screen can render one button per provider. Always present as an array (never null) and carries only the slug and display name -- never the issuer, client id, or any secret.
     */
    oidcProviders?: Array<OidcProviderSummary>;
}

