/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Claims } from './claims';
import { TokenPair } from './tokenPair';


export interface GetNewRefreshToken200Response { 
    /**
     * JWT token
     */
    jwt: string;
    /**
     * Refresh token
     */
    refreshToken: string;
    /**
     * User foreign key
     */
    userId: number;
    /**
     * Display name
     */
    displayName: string;
    /**
     * Default avatar color
     */
    defaultAvatarColor: string;
    /**
     * User\'s username used to login
     */
    username: string;
    /**
     * Issuer
     */
    iss: string;
    /**
     * Subject
     */
    sub?: string;
    /**
     * Audience
     */
    aud?: Array<string>;
    /**
     * Expiration time
     */
    exp: number;
    /**
     * Not before
     */
    nbf?: number;
    /**
     * Issued at
     */
    iat?: number;
    /**
     * JWT ID
     */
    jti?: string;
}

