/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Group member
 */
export interface GroupMember { 
    createdAt?: string;
    /**
     * Group compound primary key
     */
    groupId: number;
    /**
     * Id of the modern group role assigned to the member
     */
    groupRoleId?: number;
    updatedAt?: string;
    /**
     * User compound primary key
     */
    userId: number;
}

