/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRole } from './groupRole';


/**
 * Group member
 */
export interface GroupMember { 
    createdAt?: string;
    /**
     * Group compound primary key
     */
    groupId: number;
    groupRole: GroupRole;
    updatedAt?: string;
    /**
     * User compound primary key
     */
    userId: number;
}
export namespace GroupMember {
}


