/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OidcConnectionView { 
    providerName: string;
    providerDisplayName: string;
    preferredUsername?: string;
    email?: string;
    /**
     * Whether this connection created the local account. Such an account has no usable password, so its last connection cannot be removed.
     */
    provisionedUser: boolean;
    linkedAt: string;
    lastLoginAt?: string;
}

