/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OidcProviderSummary { 
    /**
     * The provider\'s slug, used to build its login URL
     */
    name: string;
    /**
     * Rendered to users as \"Log in with {displayName}\"
     */
    displayName: string;
}

