/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The URL a mobile client opens in the external browser to begin a \"connect account\" flow. It points back at this API, not at the identity provider, and that indirection is the point - following it is what lets the server bind the flow to the browser that will return with the callback.
 */
export interface OidcLinkStartView { 
    launchUrl: string;
}

