/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The authorization URL for a mobile \"connect account\" flow. Safe to hand to the caller - its state belongs to a session already bound to that caller\'s user id, so holding it grants nothing the bearer token did not already.
 */
export interface OidcLinkStartView { 
    authorizationUrl: string;
}

