/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OidcProviderView { 
    id: number;
    /**
     * URL slug for this provider; immutable after creation
     */
    name: string;
    displayName: string;
    /**
     * OIDC discovery base, e.g. https://accounts.google.com
     */
    issuerUrl: string;
    clientId: string;
    /**
     * Space-separated OIDC scopes; must include openid
     */
    scope: string;
    /**
     * Create a local account for an identity we have never seen
     */
    allowProvisioning: boolean;
    /**
     * On a first login only, attach to an existing local account whose username equals the preferred_username claim. Off by default; that claim is neither stable nor unique, and some providers recycle released usernames.
     */
    linkByUsername: boolean;
    enabled: boolean;
    /**
     * Whether a secret is stored. The secret itself is never returned.
     */
    hasClientSecret: boolean;
    /**
     * The exact redirect URI to register with the identity provider
     */
    redirectUri: string;
    createdAt?: string;
    updatedAt?: string;
}

