/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OidcExchangeCommand { 
    /**
     * The single-use code delivered to the app\'s callback URL
     */
    code: string;
    /**
     * The PKCE verifier the app generated before starting the flow
     */
    codeVerifier: string;
}

