/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A failure from a flow start that answers with JSON rather than a redirect. The code comes from the same small fixed vocabulary the redirect form puts in its query string, so one client-side table maps both. An identity provider\'s own error text is never echoed through.
 */
export interface OidcFlowErrorView { 
    errorCode: string;
}

