/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';
import { PermissionScope } from './permissionScope';


export interface PermissionDescriptor { 
    key: Permission;
    /**
     * Short human-readable label for the role editor.
     */
    label: string;
    /**
     * Full description used as tooltip/help text in the role editor.
     */
    description: string;
    /**
     * Logical grouping for the role editor UI (e.g., \"User Management\", \"Receipts\").
     */
    category: string;
    scope: PermissionScope;
}
export namespace PermissionDescriptor {
}


