/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How the default paid-by is resolved for optional quick-scan paid-by
 */
export type QuickScanDefaultPaidByType = 'UPLOADER' | 'USER' | '';

export const QuickScanDefaultPaidByType = {
    Uploader: 'UPLOADER' as QuickScanDefaultPaidByType,
    User: 'USER' as QuickScanDefaultPaidByType,
    Empty: '' as QuickScanDefaultPaidByType
};

