/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Where a group\'s receipt summary renders relative to its receipts list. The empty member exists so an already-released client tolerates a value added later rather than failing the whole payload; the server never sends it.
 */
export type ReceiptSummaryPosition = 'TOP' | 'BOTTOM' | '';

export const ReceiptSummaryPosition = {
    Top: 'TOP' as ReceiptSummaryPosition,
    Bottom: 'BOTTOM' as ReceiptSummaryPosition,
    Empty: '' as ReceiptSummaryPosition
};

