/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportRequestCommand } from './reportRequestCommand';


export interface ReportTemplate { 
    id: number;
    createdAt: string;
    createdBy?: number;
    /**
     * Created by entity\'s name
     */
    createdByString?: string;
    updatedAt?: string;
    /**
     * The template name (mirrors the saved report\'s name).
     */
    name: string;
    configuration: ReportRequestCommand;
    /**
     * Schema version the stored configuration was written under.
     */
    configurationVersion: number;
    /**
     * The actions the requesting user may perform on this template (read, generate, update, delete, duplicate), resolved per user and populated only on the list response. Drives the row action buttons.
     */
    allowedActions?: Array<string>;
}

