/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportColumn { 
    kind: ReportColumn.KindEnum;
    /**
     * Machine identifier; formula expressions reference this
     */
    name: string;
    label?: string;
    /**
     * Field key the column displays (dimension columns)
     */
    field?: string;
    /**
     * Aggregate function (aggregate columns)
     */
    aggFunc?: ReportColumn.AggFuncEnum;
    /**
     * Measure field key (aggregate columns, omitted for COUNT)
     */
    measure?: string;
    /**
     * Expression over other column names (formula columns)
     */
    expr?: string;
}
export namespace ReportColumn {
    export type KindEnum = 'dimension' | 'aggregate' | 'formula';
    export const KindEnum = {
        Dimension: 'dimension' as KindEnum,
        Aggregate: 'aggregate' as KindEnum,
        Formula: 'formula' as KindEnum
    };
    export type AggFuncEnum = 'SUM' | 'COUNT' | 'AVG' | 'MIN' | 'MAX';
    export const AggFuncEnum = {
        Sum: 'SUM' as AggFuncEnum,
        Count: 'COUNT' as AggFuncEnum,
        Avg: 'AVG' as AggFuncEnum,
        Min: 'MIN' as AggFuncEnum,
        Max: 'MAX' as AggFuncEnum
    };
}


