/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportPreviewResponse { 
    /**
     * The rendered report preview as a self-contained HTML document.
     */
    html: string;
    /**
     * The number of receipts the current configuration covers.
     */
    receiptCount: number;
    /**
     * The actions the requesting user may perform on the template (read, generate, update, delete, duplicate), resolved per user and populated only by the dashboard report-widget render endpoint. Drives the widget\'s download button.
     */
    allowedActions?: Array<string>;
}

