/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportTemplateOption { 
    id: number;
    name: string;
    /**
     * The ids of the groups this template covers.
     */
    groupIds: Array<number>;
}

