/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportPeriod { 
    preset: ReportPeriod.PresetEnum;
    /**
     * Start date (YYYY-MM-DD), read only when preset is custom
     */
    startDate?: string;
    /**
     * End date (YYYY-MM-DD), read only when preset is custom
     */
    endDate?: string;
}
export namespace ReportPeriod {
    export type PresetEnum = 'this_month' | 'last_month' | 'mtd' | 'qtd' | 'ytd' | 'custom';
    export const PresetEnum = {
        ThisMonth: 'this_month' as PresetEnum,
        LastMonth: 'last_month' as PresetEnum,
        Mtd: 'mtd' as PresetEnum,
        Qtd: 'qtd' as PresetEnum,
        Ytd: 'ytd' as PresetEnum,
        Custom: 'custom' as PresetEnum
    };
}


