/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportTemplateGrant { 
    reportTemplateId: number;
    /**
     * The actions a GROUP role may perform on this report template (read, generate, update, delete, duplicate).
     */
    permissions: Array<string>;
}

