/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionScope } from './permissionScope';


export interface RoleFilter { 
    scope?: PermissionScope;
}
export namespace RoleFilter {
}


