/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';
import { PermissionScope } from './permissionScope';


export interface Role { 
    id: number;
    name: string;
    description?: string;
    scope: PermissionScope;
    isSystem: boolean;
    permissions: Array<Permission>;
    /**
     * Number of users or group members currently assigned this role
     */
    assignedCount?: number;
}
export namespace Role {
}


