/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';
import { PermissionScope } from './permissionScope';


export interface Role { 
    id: number;
    name: string;
    description?: string;
    scope: PermissionScope;
    /**
     * Whether this role is the default for its scope — assigned to new accounts (APP) or to group creators (GROUP). Exactly one role per scope is the default.
     */
    isDefault: boolean;
    isSystem: boolean;
    permissions: Array<Permission>;
    /**
     * Number of users or group members currently assigned this role
     */
    assignedCount?: number;
    /**
     * Category ids a GROUP role restricts its members to. Empty means unrestricted (members may use every category). Always empty for app roles.
     */
    categoryGrants?: Array<number>;
    /**
     * Tag ids a GROUP role restricts its members to. Empty means unrestricted (members may use every tag). Always empty for app roles.
     */
    tagGrants?: Array<number>;
}
export namespace Role {
}


