/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface SignUpCommand { 
    /**
     * User\'s username
     */
    username: string;
    /**
     * User\'s password
     */
    password: string;
    /**
     * User\'s displayname
     */
    displayName?: string;
    /**
     * Whether the user is a dummy user
     */
    isDummyUser?: boolean;
    /**
     * User\'s role
     */
    userRole?: UserRole;
    /**
     * Id of the modern app role to assign. Honored by admin user creation; ignored on public sign-up, where any caller-supplied value is stripped server-side.
     */
    appRoleId?: number;
}
export namespace SignUpCommand {
}


