/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptStatus } from './receiptStatus';
import { QuickScanDefaultPaidByType } from './quickScanDefaultPaidByType';


export interface UpdateGroupReceiptSettingsCommand { 
    /**
     * Hide receipt images
     */
    hideImages?: boolean;
    /**
     * Hide receipt categories
     */
    hideReceiptCategories?: boolean;
    /**
     * Hide receipt tags
     */
    hideReceiptTags?: boolean;
    /**
     * Hide receipt item categories
     */
    hideItemCategories?: boolean;
    /**
     * Hide receipt item tags
     */
    hideItemTags?: boolean;
    /**
     * Hide receipt comments
     */
    hideComments?: boolean;
    /**
     * Hide share categories
     */
    hideShareCategories?: boolean;
    /**
     * Hide share tags
     */
    hideShareTags?: boolean;
    /**
     * Show the paid by field in quick scan
     */
    quickScanPaidByEnabled?: boolean;
    /**
     * Require the paid by field in quick scan
     */
    quickScanPaidByRequired?: boolean;
    quickScanDefaultPaidByType?: QuickScanDefaultPaidByType;
    /**
     * Default paid by user id when paid by is optional and type is USER
     */
    quickScanDefaultPaidById?: number;
    /**
     * Show the status field in quick scan
     */
    quickScanStatusEnabled?: boolean;
    /**
     * Require the status field in quick scan
     */
    quickScanStatusRequired?: boolean;
    quickScanDefaultStatus?: ReceiptStatus;
    /**
     * Show the categories field in quick scan
     */
    quickScanCategoriesEnabled?: boolean;
    /**
     * Require the categories field in quick scan
     */
    quickScanCategoriesRequired?: boolean;
    /**
     * Show the tags field in quick scan
     */
    quickScanTagsEnabled?: boolean;
    /**
     * Require the tags field in quick scan
     */
    quickScanTagsRequired?: boolean;
    /**
     * Show the comment field in quick scan
     */
    quickScanCommentEnabled?: boolean;
    /**
     * Require the comment field in quick scan
     */
    quickScanCommentRequired?: boolean;
    /**
     * Custom field ids to pre-add to every receipt created for this group. OMIT the key to leave the configured set unchanged (clients that hide this section, e.g. for a user without app.custom-fields.read, must omit it); send an empty array to clear it. Requires app.custom-fields.read - a caller without it gets a 403.
     */
    defaultCustomFieldIds?: Array<number>;
    /**
     * Also attach the group\'s default custom fields to receipts the SERVER creates (quick scan, email integration). OMIT the key to leave the stored value unchanged.
     */
    applyDefaultCustomFieldsOnIngest?: boolean;
}
export namespace UpdateGroupReceiptSettingsCommand {
}


