/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertOidcProviderCommand { 
    /**
     * URL slug. Lowercase letters, numbers and dashes. Cannot be changed after creation, and cannot be one of the reserved words login, callback, link, exchange or connections.
     */
    name: string;
    displayName: string;
    /**
     * Must use https unless the host is localhost
     */
    issuerUrl: string;
    clientId: string;
    /**
     * Omit on update to keep the stored secret. Required on create.
     */
    clientSecret?: string;
    /**
     * Space-separated OIDC scopes; must include openid
     */
    scope: string;
    allowProvisioning?: boolean;
    linkByUsername?: boolean;
    enabled?: boolean;
}

