/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpsertTaskQueueConfiguration } from './upsertTaskQueueConfiguration';
import { CurrencySeparator } from './currencySeparator';
import { CurrencySymbolPosition } from './currencySymbolPosition';


export interface UpsertSystemSettingsCommand { 
    /**
     * Whether local sign up is enabled
     */
    enableLocalSignUp?: boolean;
    /**
     * Currency display
     */
    currencyDisplay?: string;
    currencyThousandthsSeparator: CurrencySeparator;
    currencyDecimalSeparator: CurrencySeparator;
    currencySymbolPosition: CurrencySymbolPosition;
    /**
     * Whether to hide decimal places
     */
    currencyHideDecimalPlaces: boolean;
    debugOcr?: boolean;
    /**
     * Number of workers to use
     */
    numWorkers?: number;
    /**
     * Email polling interval
     */
    emailPollingInterval?: number;
    /**
     * Receipt processing settings foreign key
     */
    receiptProcessingSettingsId?: number;
    /**
     * Fallback receipt processing settings foreign key
     */
    fallbackReceiptProcessingSettingsId?: number;
    /**
     * Concurrency for task worker
     */
    taskConcurrency: number;
    /**
     * DPI used when rasterizing PDFs for OCR/vision processing
     */
    pdfDpi?: number;
    taskQueueConfigurations?: Array<UpsertTaskQueueConfiguration>;
    /**
     * Whether the OAuth 2.1-protected MCP server is enabled
     */
    mcpEnabled?: boolean;
    /**
     * Externally reachable origin used for MCP OAuth/metadata/redirect URLs and token audience
     */
    mcpPublicUrl?: string;
    /**
     * Whether to show the mobile-setup QR code on the desktop login page
     */
    showLoginQr?: boolean;
    /**
     * Server/API URL mobile clients connect to; encoded into the login QR\'s deep link
     */
    mobileServerUrl?: string;
    /**
     * How long a refresh token stays valid, in hours. 0 means unset and falls back to the default of 24.
     */
    refreshTokenValidForHours?: number;
    /**
     * How long an MCP/OAuth connector refresh token stays valid, in hours. 0 means unset and falls back to the default of 24.
     */
    mcpRefreshTokenValidForHours?: number;
}
export namespace UpsertSystemSettingsCommand {
}


