/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';
import { PermissionScope } from './permissionScope';


export interface UpsertRoleCommand { 
    name: string;
    description?: string;
    scope: PermissionScope;
    permissions: Array<Permission>;
    /**
     * Category ids to restrict a GROUP role\'s members to. Only valid on group roles; omit or leave empty for unrestricted access.
     */
    categoryGrants?: Array<number>;
    /**
     * Tag ids to restrict a GROUP role\'s members to. Only valid on group roles; omit or leave empty for unrestricted access.
     */
    tagGrants?: Array<number>;
}
export namespace UpsertRoleCommand {
}


