/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';
import { ReportTemplateGrant } from './reportTemplateGrant';
import { PermissionScope } from './permissionScope';


export interface UpsertRoleCommand { 
    name: string;
    description?: string;
    scope: PermissionScope;
    permissions: Array<Permission>;
    /**
     * Category ids to restrict a GROUP role\'s members to. Only valid on group roles; omit or leave empty for unrestricted access.
     */
    categoryGrants?: Array<number>;
    /**
     * Tag ids to restrict a GROUP role\'s members to. Only valid on group roles; omit or leave empty for unrestricted access.
     */
    tagGrants?: Array<number>;
    /**
     * User ids whose receipts a GROUP role\'s members may see (by the receipt\'s \"paid by\" user). Only valid on group roles; omit or leave empty (with includeOwnPaidReceipts false) for unrestricted access.
     */
    paidByUserGrants?: Array<number>;
    /**
     * Whether to also let each member see receipts they paid for. Only valid on group roles.
     */
    includeOwnPaidReceipts?: boolean;
    /**
     * Per-template action grants for a GROUP role, restricting which report templates its members may act on. Only valid on group roles; omit or leave empty for unrestricted access.
     */
    reportTemplateGrants?: Array<ReportTemplateGrant>;
}
export namespace UpsertRoleCommand {
}


