/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertGroupMemberCommand { 
    /**
     * Group compound primary key
     */
    groupId: number;
    /**
     * Id of the modern group role to assign to the member
     */
    groupRoleId?: number;
    /**
     * User compound primary key
     */
    userId: number;
}

