/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User in the system
 */
export interface UserView { 
    /**
     * User\'s username used to login
     */
    username: string;
    createdAt?: string;
    createdBy?: number;
    /**
     * Default avatar color
     */
    defaultAvatarColor?: string;
    /**
     * Display name
     */
    displayName: string;
    id: number;
    /**
     * Is dummy user
     */
    isDummyUser: boolean;
    updatedAt?: string;
    /**
     * Id of the modern app role assigned to the user
     */
    appRoleId?: number;
}

